### ISSUE TITLE
Separate styling in deck builder for one card missing

### ISSUE THREAD

**Issue by xtreme-brandon-sproul** [fafranco82/swdestinydb#121]
Currently, I have to hover over the card count to see if I have one copy in my collection.

A preferred approach would be grey/green for necessary number, yellow for one short, red for no copies.

**Comment by fafranco82** [comment]
Done ;)

**Comment by xtreme-brandon-sproul** [comment]
Awesome! However, if the required number of cards is 1 and I have 0, it shows orange - this should probably show red. :)

**Comment by fafranco82** [comment]
I thought that if you only need one card this will be printed as orange (2 in deck and 1 in collection, or 1 and 0), and if you need 2 of them (only it's possible if the deck uses 2 and you don't have any) then will be marked as red. I think it's most useful this way because you can know looking the colors how many cards do you need to build the deck. So if I see 2 oranges and 1 red, I know that a I need 4 more cards ;)
