### ISSUE TITLE
Reprint Cards not available in Deck Builder

### ISSUE THREAD

**Issue by ss2art** [fafranco82/swdestinydb#146]
When using the Deck Builder,  none of the cards reprinted in the Two Player Game do not show up when filtering on the set.  

Also,  in the card list for the deck, it does not take into account your inventory of these reprinted cards when color coding the number of cards in your deck.  In the attached image,  it indicates that I have no copies of **Defensive Stance** and  missing one of **Flank** (I have two copies of the cards from two set of the Two Player Game).
<img width="220" alt="screen shot 2017-09-04 at 7 32 08 pm" src="https://user-images.githubusercontent.com/17444464/30042767-339a5fc8-91a8-11e7-9581-486d4e5fef3f.png">

**Comment by fafranco82** [comment]
There is no sense in deckbuilding with reprinted cards.... the card text, abilities and names are the same, no matter where it came from. So I decide to treat reprints as if it the same card as original print (i.e. Intimidate from TPG doesn't appear because it's a reprint of Intimidate from Awakenings).

But in collection, reprints do make sense. Then, in deckbuilding, it is supposed that the quantities of cards with its reprints are summed up so if you have 1 copy of Intimidate from Awakenings and another from TPG, you will have 2 copies of Intimidate... That's on deckbuilding, I've forgotten to do the same in deck viewing ^^U

**Comment by fafranco82** [comment]
I've just fixed ;)
