### ISSUE TITLE
Issue with Deckbuilder

### ISSUE THREAD

**Issue by rebeltrooper** [fafranco82/swdestinydb#194]
Hello, You helped me delete a deck a few weeks ago. Ever since then i have not been able to edit decks or make new ones. Every time I try to change or edit a card it only gives me the option for 0. Not 1 card, or 2 cards. Chrome and Explorer browsers and neither have worked. I am not sure if that is a function what happened to remove the Rebeltroopers 7th Agro deck or if it's even an error you can fix. If the answer is to just create a new account that is fine, I just like all the Likes and Favorites i've recieved so far using your service. Thank you here are some pictures displaying what I mean.
![20180124_180324](https://user-images.githubusercontent.com/35277894/35367179-ddf0ced2-0131-11e8-8656-d4c941c0f5c7.jpg)
![20180124_180419](https://user-images.githubusercontent.com/35277894/35367183-e0530c26-0131-11e8-88bf-0dea2a633b13.jpg)

**Comment by rebeltrooper** [comment]
More importantly, Thank you for the quick resolution of my previous request! Thanks for your time again!

**Comment by fafranco82** [comment]
That's because you don't have any cards in your collection (or added them between 20th and 24th of January, when data was lost :-( ), and you have checked the 'Show only cards I owned" option in the deckbuilder. Either add cards to your collection or uncheck that option and you will can add cards to your deck ;)
