### ISSUE TITLE
Trying to add export to TableTop Simulator

### ISSUE THREAD

**Issue by w1nterl0ng** [fafranco82/swdestinydb#52]
I am working on an export to table top simulator.  I am not familiar with the "twigs" and I am finding myself doing an ad-hoc JSON build inside of a twigs file (this seems to be how octgon builds their XML).
Additionally, there is data that I need to add in order to link this to the TTS version of Destiny.  All of the cards have a different ID and an imageURL.
What is the best way to cover these two things:

1. building a JSON file, is it file to just hack it out in the twig?
2. Adding data to the system? How do we go about that at this point?

**Comment by stopfstedt** [comment]
hey @w1nterl0ng - i'd assume that the TTS identifiers and imageURLs would have to be added to this game's [data set](fafranco82/swdestinydb-json-data) first, similar to [Octagon IDs for ThronesDB](https://github.com/Alsciende/thronesdb-json-data/blob/master/schema/card_schema.json#L82).

Then, the schema and code of this application would have to be updated accordingly in order to ingest and expose these additional data points as well.

**Comment by fafranco82** [comment]
As @stopfstedt  said, if the cards has an internal ID in TTS, this must be added to JSON data set (and modify `Card` model in this project and so on). If you are not sure how to do all this, just tell me what is the format of TTS decks and I'll add it to the exports options ;)

**Comment by w1nterl0ng** [comment]
I have created a pull request with the code in my fork.  Thank you. I will close this ticket now.
